// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PubCrawlAPI;
using System;

namespace PubCrawlAPI.Migrations
{
    [DbContext(typeof(PubCrawlDbContext))]
    [Migration("20171213183608_Checkin")]
    partial class Checkin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PubCrawlAPI.Models.CheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CoordsId");

                    b.Property<string>("Name");

                    b.Property<int>("ParticipantId");

                    b.HasKey("Id");

                    b.HasIndex("CoordsId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("PubCrawlAPI.Models.Coordinates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Latitude");

                    b.Property<long>("Longitude");

                    b.HasKey("Id");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("PubCrawlAPI.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("PubCrawlAPI.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PubCrawlAPI.Models.CheckIn", b =>
                {
                    b.HasOne("PubCrawlAPI.Models.Coordinates", "Coords")
                        .WithMany()
                        .HasForeignKey("CoordsId");

                    b.HasOne("PubCrawlAPI.Models.Participant", "Participant")
                        .WithMany("CheckIns")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PubCrawlAPI.Models.Participant", b =>
                {
                    b.HasOne("PubCrawlAPI.Models.Team", "Team")
                        .WithMany("Participants")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
